[package]
name = "query-responses-hybrid-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]

syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
convert_case = "0.6"

[dev-dependencies]
schemars = "0.8.10"
cosmwasm-schema = "1.5.3"