[package]
name = "untagged-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1"
syn = { version = "2", features = ["full"] }
serde-cw-value = { version = "0.7.0" }
serde = { version = "1.0.145", default-features = false, features = ["derive"] }